spring:
  application.name: milkshake-service
  jackson.serialization.write_dates_as_timestamps: false

eureka:
  client:
    enabled: false
---
spring:
  profiles: mu

banana-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: banana-service.${_SERVICE_DISCOVERY_NAME}:8080