spring:
  application.name: milkshake-service
  jackson.serialization.write_dates_as_timestamps: false

---
spring:
  profiles: mu

banana-service:
  ribbon:
    listOfServers: banana-service.${_SERVICE_DISCOVERY_NAME}